platform :ios, '10.0'
use_frameworks!
target 'PrincessGuide' do
  pod 'SnapKit'
  pod 'FMDB'
  pod 'SwiftyJSON'
  pod 'DynamicColor'
  pod 'Kingfisher'
  pod 'KingfisherWebP'
  pod 'TTGTagCollectionView'
  pod 'AcknowList'
  pod 'ReachabilitySwift'
  pod 'Alamofire'
  pod 'lz4'
  pod 'MJRefresh'
  pod 'Gestalt'
  pod 'Timepiece'
  pod 'Tabman', :git => 'https://github.com/superk589/Tabman.git'
  pod 'Eureka'
  pod 'ImageViewer', :git => 'https://github.com/superk589/ImageViewer.git'
#  pod 'SwiftyStoreKit'
  pod 'BrotliKit'
  pod 'Cache', :git => 'https://github.com/Igor-Palaguta/Cache', :branch => 'Update-MD5'
end
