# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# setup_travis

default_platform(:ios)
xcode_select "/Applications/Xcode.app"
# match(type: "appstore", readonly: is_ci)
platform :ios do
  before_all do
    app_store_connect_api_key(
      key_id: "J626K5WZF9", 
      issuer_id: "69a6de8d-3de7-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./fastlane/AuthKey_J626K5WZF9.p8",
    )
  end
  desc "Push a new beta build to TestFlight"
  lane :beta do
    sigh(app_identifier: "com.zzk.PrincessGuide")
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "PrincessGuide.xcodeproj"
    )
    # cocoapods
    build_app(workspace: "PrincessGuide.xcworkspace", scheme: "PrincessGuide")
    upload_to_testflight
  end
  lane :clean do
    clean_testflight_testers(days_of_inactivity: 95, oldest_build_allowed: 173)
  end
  lane :export_ipa do 
    build_app(
      workspace: "PrincessGuide.xcworkspace",
      scheme: "PrincessGuide",
      export_options: {
          method: "development",
          iCloudContainerEnvironment: "Production"
      }
    )
  end
end
