# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# setup_travis

default_platform(:ios)
# xcversion(version: "11.0")
# match(type: "appstore", readonly: is_ci)
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "PrincessGuide.xcodeproj"
    )
    # cocoapods
    build_app(workspace: "PrincessGuide.xcworkspace", scheme: "PrincessGuide")
    upload_to_testflight
  end
  lane :clean do
    clean_testflight_testers(days_of_inactivity: 95)
  end
end
